### ISSUE TITLE
Using deprecated for of AWS authentication

### ISSUE THREAD

**Issue by flatherskevin** [carlpett/terraform-provider-sops#102]
I am receiving the following errors when authenticating the sops provider. Using the Mozilla sops CLI works without issue, so it appears targeted to this provider.

```
Error: Failed to get the data key required to decrypt the SOPS file.

Error decrypting key: NoCredentialProviders: no valid
providers in chain. Deprecated.
```

This error appeared when relying on the credentials passed into the `terraform init` command. I tested both raw AWS credentials, as well as profiles, and both failed.

The only way to get it to work was forcing credentials with `export AWS_PROFILE=my_profile`

**Comment by bryan-rhm** [comment]
I have not get this error, could you share how does your .sops.yaml file looks like?

**Comment by carlpett** [comment]
We do exactly what the sops cli does, so I suspect the issue is how you pass it in via Terraform. Can you share more information?

**Comment by carlpett** [comment]
Closing for lack of response
