### ISSUE TITLE
Submit GPG key for OpenTofu Registry

### ISSUE THREAD

**Issue by Gowiem** [carlpett/terraform-provider-sops#115]
## Info

* When using the SOPS provider via `tofu`, you get the following warning when it's installed (see screenshot as well): 

> Installed carlpett/sops v0.7.2. Signature validation was skipped due to the registry not containing GPG keys for this provider

* It would be great to see this get addressed. To do so, please do the following: "Submit new Provider Signing Key" from opentofu/registry's [Issues page](https://github.com/opentofu/registry/issues/new/choose). [Here is a recent example](https://github.com/opentofu/registry/issues/206). 

![CleanShot 2024-02-15 at 14 30 15](https://github.com/carlpett/terraform-provider-sops/assets/1392040/25fee9df-0783-451a-a7c7-f0fa878fe9df)

**Comment by carlpett** [comment]
Thanks, had no idea. Submitted here: https://github.com/opentofu/registry/issues/233

**Comment by Gowiem** [comment]
@carlpett working great first try! And now I've found another one where I need to go and open an issue 😄 

Thanks for being quick on this!

![CleanShot 2024-02-19 at 12 17 50](https://github.com/carlpett/terraform-provider-sops/assets/1392040/e9fa491b-422d-4725-8d9c-ef818105bdea)
