### ISSUE TITLE
data sops_file storing the secrets in tfstate

### ISSUE THREAD

**Issue by gowgopal83** [carlpett/terraform-provider-sops#117]
By using the SOPS we are no longer store the sensitive information in plain text on our git repo. However, it is still saving the secrets in plain text on tfstate data. Is there a way to avoid this? 

We use KMS to encrypt the secrets and secret manager to store the secrets.

```
data "sops_file" "fake_credentials" {
  source_file = "${path.module}/secrets/tbv3_secrets.${terraform.workspace}.secret.json"
}

resource "aws_secretsmanager_secret_version" "secrets" {
  secret_id     = aws_secretsmanager_secret.tbv3_secrets.id
  secret_string = jsonencode(data.sops_file.fake_credentials.data)
}

````

**Comment by carlpett** [comment]
Hi @gowgopal83,
As is mentioned in the first section in the readme, we assume that you have properly secured your state backend. Terraform itself does not expose any functionality that allows encrypting the state file (there are several feature requests on the Terraform repository if you would like to express interest in it).
