### ISSUE TITLE
Did you know

### ISSUE THREAD

**Issue by Korijn** [carlpett/terraform-provider-sops#12]
Did you know this also works? I just kind of found out accidentally and figured I should share it.

```
data "external" "secrets" {
  program = ["sops", "-d", "${path.module}/secrets.tfvars.json"]
}

`something = "${data.external.secrets.result["some_key"]}"`
```

Is there anything else this provider can do that the external data source cannot?

**Comment by carlpett** [comment]
Hi @Korijn,
Yes, that works, for a some cases. However, it does not (to my knowledge) support
1. Nested structures (`{"foo":{"bar":{"baz":123}}}`)
2. Yaml files

Both these cases were important in my use case. In addition, Terraform Enterprise does not work with the `external` provider, typically.

However, if none of these apply to you, then it is a valid workaround to not have to download an extra provider (tracked in #11).

**Comment by Korijn** [comment]
That is enlightening, thanks for the feedback!
