### ISSUE TITLE
Yaml lists

### ISSUE THREAD

**Issue by abeluck** [carlpett/terraform-provider-sops#13]
Does this provider support lists in yaml? I can't seem to get it to work, terraform claims that the data resource "does not have attribute" for the yaml list item.

example:

```yaml
list_of_things:
- one
- two
```

```hcl
data "sops_file" "file" {
  source_file = "file.enc.yaml"
}
locals {
  list_of_things = "${data.sops_file.file.data.list_of_things}"
}
```

**Comment by abeluck** [comment]
It seems a workaround is to specify them as comma separated strings, then when loading them in a module to split them with `split(",", data.sops_file.file.data.list_of_things)`.

This is less than ideal as it makes editing the files more error prone.

**Comment by carlpett** [comment]
Hi @abeluck,
I would have expected it to work, but since I haven't had this use-case yet, so I hadn't tested it. I can reproduce your issue, though, so obviously it doesn't. I'll see if it can be made to work!

**Comment by carlpett** [comment]
Fixed! Do note that the Golang yaml parser doesn't seem to allow "root level" lists though:
```yaml
- foo
- bar
```
They have to be under a key:
```yaml
myList:
- foo
- bar
```

To access your list elements, you'll use the normal Terraform syntax, like `"${data.sops_file.file.data.list_of_things.0}"` for example.

**Comment by abeluck** [comment]
Many thanks @carlpett  I'll give this a spin.
