### ISSUE TITLE
Use proper terraform plugin versioning

### ISSUE THREAD

**Issue by waddles** [carlpett/terraform-provider-sops#18]
It is currently not possible to specify any version of the sops provider as it does not contain a version tag. When I run a plan with `TF_LOG=DEBUG` it shows me the version numbers of all plugins but the sops version always shows `0.0.0`, for example:

```
2019/06/03 16:29:42 [DEBUG] found valid plugin: "sops", "0.0.0", "/Users/waddles/.terraform.d/plugins/terraform-provider-sops"
```

As a consequence, deleting the `~/.terraform.d/` directory and reinstalling will build the latest commit which has breaking changes to support Terraform 0.12. Also you only provide binaries for Linux so that means anyone not using Linux but still using Terraform 0.11 has to manually build the binary from an earlier commit.

Please provide binaries for other platforms and also specify the version of the plugin. No doubt this will also be required for #11

**Comment by carlpett** [comment]
Hi @waddles,
Thanks for the feedback, I'll have a look at the versioning.
Regarding the platforms, which ones do you need?

**Comment by carlpett** [comment]
Actually, from what I can tell, there still isn't any new mechanism for communicating version numbers, it is still based on the file name of the executable. For local builds, though, this isn't really clearly communicated in the readme, which should be fixed.

**Comment by carlpett** [comment]
@waddles This was auto-closed since I mentioned it in the PR, please ping me if you don't think the fix is sufficient. I pushed 0.11-compatible binaries for Windows/MacOS/Linux on the 0.2.0 release as well, so it is easier for those of you who haven't yet been able to update, hope that helps.

**Comment by waddles** [comment]
Awesome, thanks @carlpett (though I notice the artefacts for 0.2.0 also bundle the 0.3.1 version binaries).
