### ISSUE TITLE
Terraform Cloud Usage

### ISSUE THREAD

**Issue by bantonj** [carlpett/terraform-provider-sops#32]
I'm having trouble getting this to work with Terraform Cloud. Has anyone else gotten it to work? I setup the binary in terraform.d/plugins/linux_amd64/ successfully, but I'm having difficulty getting the AWS credentials working. I have it working locally with AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY environment variables, but when I setup those same environment variables in Terraform Cloud it doesn't seem to find them. It just keeps outputting the sops error of `Error: Error getting data key: 0 successful groups required, got 0`

Any tips?

**Comment by carlpett** [comment]
Hey @bantonj,
Sorry to hear that. I haven't tried using the provider with Terraform Cloud myself, I'm afraid - the client where I've primarily used it haven't migrated to TF Cloud yet.
_(Sidenot: I was actually expecting uploading 3rd party providers such as this one not to work at all (I haven't seen any documentation about it, but maybe there's something I didn't find?)... At least until the promised provider registry goes live. )_

Does other Terraform actions on KMS resources work in the same workspace? For example, `aws_kms_secrets`?

**Comment by bantonj** [comment]
I've tested again this afternoon and now it works. The only thing that I've noticed changed it the aws provider version. Maybe they were conflicting somehow.

For future reference it looks like this is working in Terraform Cloud, which is pretty cool. To get it working you need to setup the terraform-provider-sops linux binary in your local directory (and in git if you have VCS setup) like:
```
terraform.d
└── plugins
    └── linux_amd64
        └── terraform-provider-sops_v0.4.1
```
And setup sops environment variables as needed in Terraform Cloud, for AWS KMS that would be `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

**Comment by carlpett** [comment]
Cool, and thanks for describing how to get it working! :+1:

**Comment by mardinyadegar** [comment]
I am experiencing this exact issue.

**Comment by SMR39** [comment]
@mardinyadegar  any updates ?

Do we still need to push the plugin to VCS ?

**Comment by carlpett** [comment]
While I still haven't tested this myself, note that the instructions were meant to be relevant for Terraform versions before the provider registry. So think are very likely to work differently now.
