### ISSUE TITLE
Plaintext secrets in Terraform state

### ISSUE THREAD

**Issue by scjudd** [carlpett/terraform-provider-sops#33]
If you take a look at the Terraform state produced by the example in the README, you can see the plaintext secrets:

```json
{
  "version": 4,
  "terraform_version": "0.12.10",
  "serial": 1,
  "lineage": "4d2fc9e5-b6d1-9117-2a6a-419a2696783a",
  "outputs": {
    "do-something": {
      "value": "foo",
      "type": "string"
    },
    "do-something2": {
      "value": "bar",
      "type": "string"
    }
  },
  "resources": [
    {
      "mode": "data",
      "type": "sops_file",
      "name": "demo-secret",
      "provider": "provider.sops",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "data": {
              "db.password": "bar",
              "password": "foo"
            },
            "id": "-",
            "input_type": null,
            "raw": null,
            "source_file": "demo-secret.enc.json"
          }
        }
      ]
    }
  ]
}
```

This, in and of itself, is not abnormal for a Terraform provider that handles secrets; however, it caught a coworker of mine off-guard.

If it's not possible to store ciphertext/hashes/whatever in the state, can we at least put a big disclaimer somewhere that this is the case and heavily recommend using an encrypted backend state store?

**Comment by carlpett** [comment]
Hi @scjudd,
As you mention, this is expected behaviour, and how all Terraform providers work. But the readme can definitely be improved! If you have a few spare minutes, feel free to make a PR suggesting a wording that would have prepared your colleague :)

**Comment by perryao** [comment]
@carlpett could this be avoided by defining a [SchemaStateFunc](https://pkg.go.dev/github.com/hashicorp/terraform/helper/schema#SchemaStateFunc)? So that only a hash or something is stored in state?

There's a `StateFunc` field on the `Schema` struct defined [here](https://github.com/hashicorp/terraform-plugin-sdk/blob/7a6c389c131a660c9e08c8037ac3f4824aab95d7/helper/schema/schema.go#L141)

**Comment by fmaylinch** [comment]
@perryao Currently I am dealing with this issue. As far as I've seen, the `StateFunc` is applied for input strings at root level, and it doesn't work for `Computed`, or other types, or strings embedded in other types (lists, maps, etc). So, if you're developing your own resources, I guess that you could define all sensitive inputs as simple strings at root schema level.

**Comment by kfkawalec** [comment]
Maybe it's is good idea to remove date from state file? :)
There is any reason to not doing this? (other that "this is bad")
terraform state rm data.sops_file.tfvars
