### ISSUE TITLE
Cannot use yaml dictionaries to populate terraform map() type

### ISSUE THREAD

**Issue by abeluck** [carlpett/terraform-provider-sops#41]
I have a terraform 12 module that accepts a `map(string)` as an input variable. (They are tags eventually passed to AWS).

Example sops encrypted yaml file:

```
tags:
  bar: 'one'
  jax: 'two'
```
In my terraform module i'd have something like:

```hcl
locals {
  tags =  data.sops_file.secrets.data["tags"]
}
```

But this errors with : 
```
Error: Invalid index
  on vars.tf line 12, in locals:
  12:   tags       = data.sops_file.secrets.data["tags"]
    |----------------
    | data.sops_file.secrets.data is map of string with 20 elements
The given key does not identify an element in this collection value.
```

**Comment by carlpett** [comment]
Hi @abeluck,
While this worked in Terraform 0.11, that was apparently an "accidental feature", and no longer works in 0.12 (but coming back sometime in 0.13 hopefully!). For now, this should work:
```hcl
locals {
  tags = yamldecode(data.sops_file.secrets.raw).tags
}
```

**Comment by abeluck** [comment]
Thanks @carlpett  that workaround works!

**Comment by carlpett** [comment]
:+1:
