### ISSUE TITLE
Migration Steps from 0.11 provider blocks to 0.12.20+/0.13 required blocks

### ISSUE THREAD

**Issue by Smuggla** [carlpett/terraform-provider-sops#44]
Just went through this so its not really an issue, more of a migration guide. If people think it should be added to a troubleshooting README, I can create a pull request.

Originally, we had been using the sops provider via `wget` to local `~/.terraform.d/plugins/`
then calling
```
provider "sops" {}
```

With terraform 0.12.20 and in 0.13 you can call it via a `required_providers` block (Yay!)
```
    sops = {
      source = "carlpett/sops"
      version = "0.5.1"
    }
```

What happens when you change to this is that it creates a new provider then the one that was used previously.
```
- Finding carlpett/sops versions matching "0.5.1"...
- Installing carlpett/sops v0.5.1...
- Installed carlpett/sops v0.5.1 (self-signed, key ID 1468AC14E6819667)
```

But if you have used the sops provider previously, after the upgrade you will get a error:

```
- Finding latest version of -/sops...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider -/sops:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/-/sops
```

That is because, in the state file the original provider still exists  

```
terraform providers
Providers required by configuration:
.

└── provider[github.com/carlpett/sops] 0.5.1


Providers required by state:

    provider[registry.terraform.io/-/sops]
```

To update this you must remove the data source from your `terraform.state` file.

Once this has been done and the init has been re-ran you are now using the new provider and can proceed.

Thanks!

**Comment by carlpett** [comment]
Hey @Smuggla,
Thanks for sharing this! I think it would definitely make sense to have in the readme, as many people will make this transition soon.

**Comment by BowlingX** [comment]
I just upgrade to `0.13.0` and used `terraform state replace-provider registry.terraform.io/-/sops registry.terraform.io/carlpett/sops` to make it work.

**Comment by teochenglim** [comment]
I just upgrade to terraform 0.13.0 and used terraform state replace-provider registry.terraform.io/-/sops registry.terraform.io/carlpett/sop works for me if I have other repo and remote state.

**Comment by carlpett** [comment]
I've updated the docs to include these commands. Thanks!
