### ISSUE TITLE
Terraform Cloud usage with PGP keys always shows it will change the values, but it doesn't which is confusing. 

### ISSUE THREAD

**Issue by ursuad** [carlpett/terraform-provider-sops#48]
Hi, I'm using this module in Terraform Cloud. I added binary under the `terraform.d/plugins/linux_amd64/terraform-provider-sops_v0.5.1` path. 

Terraform version: `v0.12.29`
SOPS Provider version: `v0.5.1`

The plan always shows as the values will be changed, but after an apply, I can see that the values are not actually changed (which was what I expected) initially. 
This makes things very confusing, because you don't know what will be changed beforehand (all the places where the SOPS data sources are used will show like candidates for changing during plan) but they won't actually be changed if the values haven't. (which you can only see after the apply). 
This happens becuase of [this](https://www.terraform.io/docs/configuration/data-sources.html#data-resource-dependencies):
```
In particular, the depends_on meta-argument is also available within data blocks, with the same meaning and syntax as in resource blocks.

However, due to the data resource behavior of deferring the read until the apply phase when depending on values that are not yet known, using depends_on with data resources will force the read to always be deferred to the apply phase, and therefore a configuration that uses depends_on with a data resource can never converge.

Due to this behaviour, we do not recommend using depends_on with data resources.
```

Is there another (better) way to import the private PGP key, or any other suggestions on how this could be fixed? 
 

In this case, the cloud Provider is Yandex, so we're using PGP for the encryption of secrets using SOPS. 

To be able to to import the private PGP key in Terraform Cloud, I defined a resource like this:
```
resource "local_file" "gpg_import" {
  sensitive_content = base64decode(var.my_sops_private_key_b64_secret)
  filename = "${path.root}/my_sops_pgp_private_key.asc"
  provisioner "local-exec" {
    command = <<EOH
gpg --import ${path.root}/my_sops_pgp_private_key.asc
EOH
  }
}
```
And I read the secret encrypted files like this:
```

data "sops_file" "yandex_secrets_sops" {
  source_file = "secrets/yandex_secrets.enc.yaml"
  depends_on = [local_file.gpg_import]
}
```
and I use one of those values in the secret file, to define a password for the database like this:
```

module "rc_db" {
  source  = "app.terraform.io/MY_POSTGRESQL_YANDEX_MODULE"
  version = "0.1.0"
  db_cluster_name     = "some-val"
  db_vpc_id           = "some-val"
  db_subnet_id        = "some-val"
  db_name             = "some-val"
  db_owner            = "db_owner"
  db_password         = data.sops_file.yandex_secrets_sops.data["yandex_db_password"]
  db_assign_public_ip = true
}
```

The problem is anytime I do a `plan`:
•  it shows me that it will create the new resource (`local_file.gpg_import` which is expected) as each  TF cloud run is on a different worker
• it shows that it will update the data source `data.sops_file.yandex_secrets_sops`
• it also shows that it will change the resource for the data base in place, but the values haven't changed and that's not correct. 
``` 
  # data.sops_file.yandex_secrets_sops will be read during apply
  # (config refers to values not yet known)
 <= data "sops_file" "yandex_secrets_sops"  {
      + data        = (known after apply)
      + id          = (known after apply)
      + raw         = (known after apply)
      + source_file = "secrets/yandex_secrets.enc.yaml"
    }

  # local_file.gpg_import will be created
  + resource "local_file" "gpg_import" {
      + directory_permission = "0777"
      + file_permission      = "0777"
      + filename             = "./my_sops_pgp_private_key.asc"
      + id                   = (known after apply)
      + sensitive_content    = (sensitive value)
    }


------------------ Omitted ------------------ 
          - user {
          - grants   = [] -> null
          - login    = true -> null
          - name     = "db_owner" -> null
          - password = (sensitive value)

          - permission {
              - database_name = "some-val" -> null
            }
        }
      + user {
          + grants   = []
          + login    = true
          + name     = "db_owner"
          + password = (sensitive value)

          + permission {
              + database_name = "some-val"
            }
        }
```
But when I do an `apply`, the only resource that gets changed is the `local_file.gpg_import`. 
Which is very confusing, as you don't know what the changes will be before the actual run.

**Comment by carlpett** [comment]
Hi @ursuad,
As you note, this is inherent in how Terraform data sources work with `depends_on`. Everything dependent on that data source is then marked as being unavailable until apply. So what you are seeing is the expected behaviour, and nothing that can be changed as such in this provider.
That said, there are options. I'd say the _best_ solution here would probably be to implement support for [Yandex KMS](https://cloud.yandex.com/services/kms) in SOPS itself, which would bypass the entire problem with importing keys.
Another way to solve this without provisioners would be to make this provider accept a key as an input and import it during initialization. This seems like a bit of a kludge, though...
If you'd be comfortable adding the support in SOPS, I can update the provider here to support the new version.

**Comment by ursuad** [comment]
Sure thing, was thinking the same with the SOPS support for Yandex. I'll try to create a PR to support Yandex for SOPS. 
I think, if I remember correctly that TF 0.13 might fix this. 
In the meanwhile, this can be closed as it's not an issue with the SOPS provider.
