### ISSUE TITLE
does not have a provider named registry.terraform.io/hashicorp/sops

### ISSUE THREAD

**Issue by mabushey** [carlpett/terraform-provider-sops#55]
This provider does not seem to work with Terraform .12 under Linux (Ubuntu):
```
wget https://github.com/carlpett/terraform-provider-sops/releases/download/v0.5.3/terraform-provider-sops_0.5.3_linux_amd64.zip
unzip terraform-provider-sops_0.5.3_linux_amd64.zip
mv terraform-provider-sops_v0.5.3 ~/.terraform.d/plugins/

✗  terraform --version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.43.0
+ provider registry.terraform.io/hashicorp/google-beta v3.43.0
+ provider registry.terraform.io/hashicorp/local v2.0.0

✗  head -n1 sops.tf 
provider "sops" {}

✗  terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/google v3.43.0
- Using previously-installed hashicorp/local v2.0.0
- Using previously-installed hashicorp/google-beta v3.43.0
- Finding latest version of hashicorp/sops...

Error: Failed to install provider

Error while installing hashicorp/sops: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/sops

**Comment by mabushey** [comment]
The instructions here worked: https://registry.terraform.io/providers/carlpett/sops/latest

Looks like the install docs just need to be updated.

**Comment by rindeastwood** [comment]
Same issue here.
@mabushey , i dont see instructions on https://registry.terraform.io/providers/carlpett/sops/latest, except the "use provider" part. Which instructions have you followed?

**Comment by rindeastwood** [comment]
My issue was related to the fact, that non-hashicorp providers must be defined in all modules as well.

**Comment by mabushey** [comment]
@rindeastwood Yes, the `Use Provider` part. Once I dropped that in and did a `terraform init` it worked.

**Comment by vfiset** [comment]
@rindeastwood you saved me! I did not understand that from reading the doc. Now that I've read your comment it opens my eyes 😸

**Comment by fralvarop** [comment]
I got my main.tf like this:
`provider "sops" {}

data "sops_file" "secrets" {
  source_file = "terraform-secret.enc.json"
}`

and I get this error when doing a terraform init:
`Error: Failed to install provider

Error while installing hashicorp/sops: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/sops`

Can someone tell me what to do?

**Comment by carlpett** [comment]
The docs in the repo are updated now, and should be more helpful :)

**Comment by danpalmer** [comment]
Hi all, I'm still having this problem having followed the docs. I'm on Terraform 0.13.6, having just upgraded. I've done the upgrade step (replace-provider) in the readme, and I'm using this:

```hcl
terraform {
  required_providers {
    sops = {
      source = "carlpett/sops"
      version = "0.6.0"
    }
  }
}

provider "sops" {}
```

Still getting this error though:

```
Initializing provider plugins...
...
- Using previously-installed carlpett/sops v0.6.0
- Finding latest version of hashicorp/sops...

Error: Failed to install provider

Error while installing hashicorp/sops: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/sops
```

Have I missed a step?

**Comment by vfiset** [comment]
@danpalmer yes, you have missed this step probably https://github.com/carlpett/terraform-provider-sops/issues/55#issuecomment-744594206

**Comment by danpalmer** [comment]
Right, I had the provider declared in my top-level module, but in the nested module that uses it I had only done `provider "sops" {}`, but it requires the full `terraform` block (which I didn't realise was used below the top level), the required version, etc.

It looks like it's working now – the full specification of the provider is required in every module it's used, that's the bit I didn't understand.

Thanks!

**Comment by Snehil03** [comment]
Hello,
I am currently running terraform v0.13.2 ,
I have added required_providers block and added sops source and version. 
But my terraform init still look for old sops any way to fix these issue ?

terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed carlpett/sops v0.6.0
- Using previously-installed hashicorp/kubernetes v1.13.1
- Using previously-installed hashicorp/helm v1.3.0
- Using previously-installed hashicorp/aws v3.29.1
- Using previously-installed hashicorp/local v2.1.0
- Using previously-installed hashicorp/null v3.1.0
- Using previously-installed hashicorp/random v3.1.0
- Using previously-installed hashicorp/external v2.1.0
- Finding latest version of hashicorp/sops...

Error: Failed to install provider

Error while installing hashicorp/sops: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/sops

**Comment by Snehil03** [comment]
@danpalmer :  what do you mean by full terraform block in module ?
May be I am missing same steps, 
Could you post how does module look like with terraform block and provider ?

**Comment by danpalmer** [comment]
We had something like this...

In our "root" module, we had:

```terraform
terraform {
  required_providers {
    sops = {
      source = "carlpett/sops"
      version = "0.6.0"
    }
  }
}

# ... terraform code, using nested module

```

Then in the "nested" module we _incorrectly_ had:

```terraform
resource "sops" "something_using_sops" {}  # ... etc
```

I had assumed that the sops provider only needed to be declared in the root module, and that it would be "inherited" by other modules, but this was incorrect. I think I got here through a lack of understanding of Terraform and also the fact we had done a Terraform 12->13->14 migration in one go, and I think this changed a bit in that process.

*In fact, in the nested module _also_ needs the `terraform` block that was present in the root module.*

In our case, we actually don't use sops at the top level, only in some of our nested modules, so I pushed the config down, removing it from the top level and adding it to the lower level.

I hope this helps.

**Comment by Snehil03** [comment]
Yes, Indeed it was helpful.
I were able to fix the issue, I missed to execute terraform upgrade0.13 command , hence it was causing that issue.

I executed it and ran terraform init ...
all seems to be aligned and back in place.
