### ISSUE TITLE
Publish latest version to Terraform registry

### ISSUE THREAD

**Issue by ibratoev** [carlpett/terraform-provider-sops#56]
It seems the latest version is not pushed to the Terraform registry: https://registry.terraform.io/providers/carlpett/sops/latest .
Consider automating the process.

**Comment by carlpett** [comment]
Hi,
I noticed the same a couple of hours ago. The automation is in fact in place, but something appears to have malfunctioned on the registry side. I've contacted Hashicorp and asked for assistance, hope to have some assistance soon.

**Comment by carlpett** [comment]
It's been fixed now!
