### ISSUE TITLE
cannot use non-json raw file

### ISSUE THREAD

**Issue by xelalexv** [carlpett/terraform-provider-sops#59]
Terraform: 0.14.5
SOPS plugin: 0.5.3

I'm having trouble with using a raw file that is not JSON:

Template:
```Terraform
provider "sops" {}

data "sops_file" "dbauth" {
    source_file = "dbauth.env"
    input_type = "raw"
}

output "dbauth" {
    value = data.sops_file.dbauth.raw
}
```

Decrypted content of dbauth.env:
```
#
# Don't use quotes around values!
#
db-password=myPassword
```

When running `terraform plan`, I get:
```bash
10:23 $ terraform plan

Error: Error unmarshalling input json: invalid character '#' looking for beginning of value

  on sops.tf line 3, in data "sops_file" "dbauth":
   3: data "sops_file" "dbauth" {
```

Am I missing out on anything? Is this supposed to work with arbitrary raw data?

**Comment by carlpett** [comment]
Hi @xelalexv,
I'm unable to reproduce this, I'm afraid. I'm at the exact same versions as you are, with the same file content, except for adding a `required_providers` block.
What does your encrypted file look like? By the error message, I would almost suspect it is trying to read the decrypted version of the file.

**Comment by xelalexv** [comment]
When I reference a JSON file encrypted with the same key, everything works. I also tried and removed the three comment lines from the content given above and encrypted that. In that case, I get the same error message, only this time with `invalid character 'd' looking for beginning of value`, so it seems it is correctly decrypting the file. Anything else I can try?

**Comment by carlpett** [comment]
Here's the files I test with:
`main.tf`
```hcl
terraform {
  required_providers {
    sops = {
      source = "carlpett/sops"
      version = "~> 0.5"
    }
  }
}

provider "sops" {}

data "sops_file" "dbauth" {
    source_file = "dbauth.env"
    input_type = "raw"
}

output "dbauth" {
    value = data.sops_file.dbauth.raw
}
```

`dbauth.env`
```json
{
        "data": "ENC[AES256_GCM,data:KiyU30KMkaB66sghvyjoE6ac31qO7h6215tCJA0xUvE2IDgIpQKVYZm2Z1ARVtck51VarbmwbL77VZDF5A==,iv:4gd0nkDASguSir+sM7Re6ZLj1DFaEel+sdBbEOhvOU4=,tag:nmd8MqrVLobDfsvLjsnoxw==,type:str]",
        "sops": {
                "kms": null,
                "gcp_kms": null,
                "azure_kv": null,
                "hc_vault": null,
                "lastmodified": "2021-01-24T20:02:43Z",
                "mac": "ENC[AES256_GCM,data:PET2a6S9KpjpCaQ83kqp3RBwYbepQ8UxKzAbMbAvjWIcQ+RMVA8IuTXOnQ0pD0pxynzO/Od9vk4JkTNA/TEJ7RZAeGGQvzkaMHojjFAurzW3EOjPuEMfWflibhQeulFiY/IJImyoNmjDuNcW3b9/Q8kJMSw0lE/mpAuY3NFamfo=,iv:FzNitFnAzZ0WNm7DSED96FDUxqawp3uRYGmVQ7qTVpQ=,tag:MRgqS61za0CfFOoIuUBowg==,type:str]",
                "pgp": [
                        {
                                "created_at": "2021-01-24T20:02:38Z",
                                "enc": "-----BEGIN PGP MESSAGE-----\n\nhQEMA/FdPFBXWyBuAQgAhi95ZQvGbB1ow1l9EVmlEsTVUBXObBj3ev3uo8MnvsSF\na7ENw7cIxYG/6mCyrly522QjbGtdjtGV7F93OPLgA1psWVC3Xjr15nvrj7Si5Rfv\nRk6vT5iTIo/rBsiQxTm7Pnaf8+CpGuR7SCNa0VPX/3PRI/hulx/kvzRDBsFbF86/\nRm2eDVZ3Z8fvCJfxJwrBWMMySFjLBsxAixVcQICoxSWFAY7l0+y8kdshPpLQngQv\nxBrvd60omS6RsVeLaF4YjQRvOv5bwLrjABOyk7z6tni/pLIb86ACc5/vQq/0Gjb4\naSD3cP2OO609MWLlH8p4cghGLY6mliI9jXUGxoYV9tJeAUeTyC1Yj55COWsIJQ6X\nfFg+X9aa2LRSeckR+Hfaw5JWXo2QP1H75P1dQ/uu7n1qnNjmV7EmE4cDkMSGzKXh\nErkmdOFiqXByrm1B5WpbLmGmisWTru84zFM+c6xuLg==\n=JUDq\n-----END PGP MESSAGE-----\n",
                                "fp": "BF36CD3D0749A11A"
                        }
                ],
                "unencrypted_suffix": "_unencrypted",
                "version": "3.6.1"
        }
}
```

The encrypted file was created with `sops -p BF36CD3D0749A11A dbauth.env`, where `BF36CD3D0749A11A` is the fingerprint of the unit test key in this repo, which you can import with `gpg --import test/testing-key.pgp`. Does this work for you? If not, can you see if you can figure out the difference between this and your case?

**Comment by xelalexv** [comment]
I think I found the root cause. Quoting from the Sops docs:

> sops uses the file extension to decide which encryption method to use on the file content. YAML, JSON, ENV, and INI files are treated as trees of data, and key/values are extracted from the files to only encrypt the leaf values. The tree structure is also used to check the integrity of the file.

So `env` files are treated by sops similar to JSON and YAML, and not actually as binary files, i.e `raw` in the sense of the Terraform sops provider. When running `sops -e db-auth.env` (I have a `.sops.yaml` in place for choosing keys), I hence get:
```
#
#ENC[AES256_GCM,data:qbMOePKjf/qfk/XEGGbaP+oDBs/D/uZ20fU0EilP8Y8=,iv:lT8Q8TDML5SOLWVx7knMv+z5kupj/1miLa7d1buHy5w=,tag:UJkKsAH3uLaNXSstHn5caw==,type:comment]
#
db-password=ENC[AES256_GCM,data:RzTHBLVCLgk=,iv:8udUTVHftLAS58q53HlgnvZaiYCH6avs+L/G2/Wfs4M=,tag:hoxFe+GuNe8JQEsgtdSZYw==,type:str]
sops_lastmodified=2021-01-25T09:12:05Z
sops_pgp__list_0__map_enc=-----BEGIN PGP MESSAGE-----\n\nhQGMA4jlewsfDm1HAQwAruYTQ9TtESti2eJm7qvW/Wy2eqr010w0ca7siHz5MmkX\nN90i87RqKd/dnr4apoC+pgg7Ma2ToK+QXBaQ+mK5cDH3VRrE+ugQ6SsJxw53Gs3T\nq3TTvRO3V8Z1M8YgA1bEUhXqi2qdz5x8OthKoe6IPpDD5Yof5v306qM/QPn2YIPE\nP4xGODjU2TPnwgiRMgVOJa6kq99H2RSNX6FxZztX0Tzf+t6+RBLJsyu7/Bwl0bdC\nbtD5xxSnwYfFOW11KEAVXXeW4v9dXbFLwjQpjqUbwoogZYaH8fGr0pxzdhqEwVDB\np0BxtWDJR2djWHMlJV8CYQ4pKa+qrvGZnthpDanSgrC4bZef9O4r1QAtRIluT3a6\nsrXM2kD1bLT82SXEVqPmWVzIYJezLXbDIdMNmsupqRqBbSrIrOefglnsl9ahe10S\nEkqa1GucfISaMwQJwkujET53RzrSiDYIQYg7uIt1Fw7oOHUfQMaxGGrf/u9X65lO\n1mEH/72ExEvWokWxDtQ70l4BFj2olyJsg93DoNqoQEPtZ89lgDfqqeQzrm2v48qa\nGbOGjA/fHXxcP8AA1v7a4kiz2C7D/Gl7SKytObYAchKBq/ufz8o8NzN9Um3BQ5pU\nmjbh8r/W/zEJlMYQKmy1\n=z308\n-----END PGP MESSAGE-----\n
sops_pgp__list_0__map_created_at=2021-01-25T09:12:04Z
sops_mac=ENC[AES256_GCM,data:6IlUMAng2mxTSq1aKadACd1tNDzHotuvoFFfhcmwzUN5sWFsITXAW/yeAbhW3HA2mCwerYac6pU1OR51O/5rw1EipaL9r5JUtbMsg85+zMzZo5ue+lS0IiiXpOtl/F+dSzljJ4CMKU75A+t6gpzk03eXl8K4SrdaQdB+UsDQU70=,iv:+9KBrHNblJlInldgs+FEpmGPKHyaynOfPOE3Qbu62j8=,tag:FpDQltZs3xTQxm0FtC3/yg==,type:str]
sops_unencrypted_suffix=_unencrypted
sops_version=3.6.1
sops_pgp__list_0__map_fp=6A00979BA96CACE1F1E8DE804FFD11334AC4452D
```
This is different from your encrypted file. Question is, why sops in your environment treats the env file as binary data. BTW, my sops version is 3.6.1. Not sure whether the handling of env files is something that was added to sops recently.

I then created `db-auth.bin` with the same content, encrypted it, and with that, everything works. So I guess this issue is actually more about adding support for env files.

**Comment by carlpett** [comment]
Oh, well that'd explain it! I wasn't aware that .env files were treated in a special way, that must be pretty new.
Updating my local sops binary, it indeed creates another output, matching yours, and the error also matches yours.

We'll need to add support for the new format (and .ini, I suppose). Until then, encrypting it under a different name to avoid triggering the .env behaviour is a workaround.

**Comment by carlpett** [comment]
@xelalexv Your case should now work with v0.6.0 :slightly_smiling_face:

**Comment by xelalexv** [comment]
Brilliant! I can confirm it's working in my setup. Thanks a lot!
