### ISSUE TITLE
Do we still need a blank sops provider?

### ISSUE THREAD

**Issue by heydonovan** [carlpett/terraform-provider-sops#66]
```
provider "sops" {
  # left blank on purpose
}
```

We are in the process of upgrading from Terraform 0.12 to 0.15. Do we still need this blank line? Doesn't seem like it.

**Comment by carlpett** [comment]
Hi @heydonovan,
No, that's no longer needed. Just adding it under `required_providers` block is sufficient. Nice catch, I'll update the docs!
