### ISSUE TITLE
"Error getting data key: 0 successful groups required, got 0" - GitHub Actions

### ISSUE THREAD

**Issue by enchorb** [carlpett/terraform-provider-sops#81]
Hi All, 

Seem to be running into this issue when running through GitHub Actions. 

Locally this sops provider works great, gcloud auth application-default impersonates a service account with 'owner' permissions and get no errors on terraform apply.

In GA, we are using Workload Identify Federation which also impersonates the same service account, yet we get this error on the sops step to decrypt our env file. If I comment out the sops module then it builds fine so workload identify federation is working.

I can provide code if required but from a high level is there anything I'm missing? Does this provider not work with WLIF?

**Comment by enchorb** [comment]
May be related? https://github.com/mozilla/sops/issues/969

**Comment by multani** [comment]
@enchorb The provider v0.7.1 contains an updated version of sops that supports credentials returned by the workload identity federation on GCP, would it be possible to try again and see if that new version fixed your issue?

**Comment by enchorb** [comment]
Getting this error now:

```
Group 0: FAILED
  projects/project_name/locations/us-central1/keyRings/env-key-ring/cryptoKeys/env-crypto-key: FAILED
    - | Error decrypting key: googleapi: Error 403: Permission
      | 'cloudkms.cryptoKeyVersions.useToDecrypt' denied on resource
      | 'projects/project_name/locations/us-central1/keyRings/env-key-ring/cryptoKeys/env-crypto-key'
      | (or it may not exist)., forbidden
```

This is different than the old error:

```
Group 0: FAILED
  <*** path to GCP keyring ***>: FAILED
    - | Cannot create GCP KMS service: google: error getting
      | credentials using GOOGLE_APPLICATION_CREDENTIALS environment
      | variable: unknown credential type: "external_account"
```

The account with WLIF has `Owner` permissions so not entirely sure why it would be returning a 403, and it works locally

**Comment by multani** [comment]
> unknown credential type: "external_account"

Hm, can you double check you are using the right version of the provider? This particular error should have been fixed by sops itself, and bundled as part of the v0.7.1 version of the provider.
