### ISSUE TITLE
Version updgrade to fit with Sops v3.7.2

### ISSUE THREAD

**Issue by p0bailey** [carlpett/terraform-provider-sops#84]
Hello,

Sops v3.7.2 has recently been released, are there any plans to upgrade the plugin? 

https://github.com/mozilla/sops/releases/tag/v3.7.2

Best,

Phillip

**Comment by carlpett** [comment]
Hi @p0bailey,
Version 0.7.0 was just released (after me forgetting to promote the prerelease for a week), and has 3.7.2!

**Comment by p0bailey** [comment]
Hi @carlpett thanks so much, really appreciated!

Phillip
