### ISSUE TITLE
Invalid index error using terraform import

### ISSUE THREAD

**Issue by BroderPeters** [carlpett/terraform-provider-sops#92]
While my current sops setup works for the `terraform plan` operation, it doesn't seem to work with the `terraform import` operation.
I'm setting up a provider and one resource with the following setup.
```terraform
data "sops_file" "secrets" {
  source_file = var.secret_file_path
}

provider "slack" {
  token = data.sops_file.secrets.data["slack.token"]
}
```
```yaml
[some secrets]
slack:
    token: abcdefg
```

While during `terraform init`, `terraform plan` and `terraform apply` everything works flawless, I get the following error trying to `terraform import` an existing resource to the terraform managed one:
```bash
╷
│ Error: Invalid index
│ 
│   on /home/bp/src/kineo/common-resources-infrastructure/aws/slack.tf line 29, in provider "slack":
│   29:   token = data.sops_file.secrets.data["slack.token"]
│     ├────────────────
│     │ data.sops_file.secrets.data has a sensitive value
│ 
│ The given key does not identify an element in this collection value.
╵
```
If I provide the token "directly" without sops, the import works.
Is that a bug or am I missing something?

**Comment by carlpett** [comment]
Hi @BroderPeters,
I would have expected this to work, and am unsure why it wouldn't. I can't easily reproduce it, though. Could you try running the import with environment `TF_LOG=1` and share relevant log lines?
My best guess is that the data source isn't initialized properly during the import, but it's hard to know exactly why.

**Comment by BroderPeters** [comment]
Thanks for the fast response!

Funny thing: I just wanted to provide you with more information, like you asked, but now it works! 🤷🏻 
I did some minor related general changes in terraform, but the above described setup was still the same.
I guess it was only some local hiccup, as the only different thing from yesterday would be a reboot of my laptop.
