### ISSUE TITLE
sops does not work with a transit-key created under a vault sub namespace

### ISSUE THREAD

**Issue by linuxbsdfreak** [carlpett/terraform-provider-sops#97]
Hi.

One has to explicitly set the following **export VAULT_NAMESPACE=basens/subnamspace** before a terraform plan/apply  when decrypting a sops file with a transit key from vault. The vault transit key is under **basens/subnamspace** . There should be a way to set it under the **data "sops_file"**  resource

```
data "sops_file" "secrets" {
  source_file = join ("/", [ "/tmp", "${local.cluster_name}.secrets.enc.json" ])
  input_type = "json"
  **vault_namepsace = "basens/subnamspace"**

  depends_on = [ local_sensitive_file.secrets_file ]
}
```

**Comment by carlpett** [comment]
Hi,
The provider won't try to cover all possible parameters to the underlying sops key managers (note also that the `sops` CLI itself does not expose flags for these either). Instead, you should do what you are already doing, and set the corresponding environment variables.
