### ISSUE TITLE
0.7.2 macos/arm m1 issue

### ISSUE THREAD

**Issue by rsavage-nozominetworks** [carlpett/terraform-provider-sops#99]
When using 0.7.2 on Linux/amd64 the 0.72 version of the provider works great.  However, when using this version on an arm mac (m1), seeing the following error.   Looks like the hash signature is wrong?

```
╷
│ Error: Failed to install provider
│
│ Error while installing carlpett/sops v0.7.2: the current package for registry.terraform.io/carlpett/sops 0.7.2
│ doesn't match any of the checksums previously recorded in the dependency lock file; for more information:
│ https://www.terraform.io/language/provider-checksum-verification
╵
```

**Comment by carlpett** [comment]
Hi @rsavage-nozominetworks,
Is it possible the lockfile was generated on a machine with another architecture? You can fetch missing platform hashes by calling `terraform providers lock -platform darwin_arm64`.

**Comment by rsavage-nozominetworks** [comment]
@carlpett No, the lock file is not getting generated with another architecture.  This issue only happens with this provider on macs with the ARM silicon.  I've tried it on different clean mac (m1) and the issue is reproducible.   Does not happen with Linux, and does not happen with version 0.7.1 on mac-m1-arm.  I can download the binary of 0.7.2, but I still get the checksum error.   I suspect there's a problem with the checksum.

**Comment by carlpett** [comment]
Very odd. From what I can tell, the checksum is the same in the SHA256SUMS file as the binary that was generated in the release build (`43f218054ea3a72c9756bf989aeebb9d0f23b66fd08e9fb4ae75d4f921295e82`). Do you have a way to tell what you're getting?

**Comment by bryan-rhm** [comment]
@rsavage-nozominetworks I tested on M1 and works great, can you try deleting your folder `.terraform` and `terraform.lock.hcl` and run the terraform init again ?

**Comment by carlpett** [comment]
Closing for lack of feedback.
